test_that("it should create a type", {
  t <- type("date", format = "%Y-%m-%d")
  expect_true(t == "date")
  expect_equal(class(t), c("type", "date"))
  t <- type("time", format = "%H:%M:%S")
  expect_true(t == "time")
  expect_equal(class(t), c("type", "time"))
  t <- type("datetime", format = "%Y-%m-%d %H:%M:%S")
  expect_true(t == "datetime")
  expect_equal(class(t), c("type", "datetime"))
  t <- type("numeric", dec = 0, sign = "+")
  expect_true(t == "numeric")
  expect_equal(class(t), c("type", "numeric"))
  t <- type("number")
  expect_true(t == "number")
  expect_equal(class(t), c("type", "number"))
  t <- type("integer")
  expect_true(t == "integer")
  expect_equal(class(t), c("type", "integer"))
  t <- type("character")
  expect_true(t == "character")
  expect_equal(class(t), c("type", "character"))
  t <- type("logical")
  expect_true(t == "logical")
  expect_equal(class(t), c("type", "logical"))
  # t <- type("factor", levels = c("A", "B", "C"), labels = c("Alpha", "Beta", "Gamma"))
  # expect_equal(class(t), c("type", "factor"))
})

test_that("it should parse a character to a type", {
  s <- "date"
  t <- type_parse(s)
  expect_true(t == "date")
  expect_true(t$format == "%Y-%m-%d")
  expect_equal(class(t), c("type", "date"))
  s <- "time"
  t <- type_parse(s)
  expect_true(t == "time")
  expect_true(t$format == "%H:%M:%S")
  expect_equal(class(t), c("type", "time"))
  s <- "datetime"
  t <- type_parse(s)
  expect_true(t == "datetime")
  expect_true(t$format == "%Y-%m-%d %H:%M:%S")
  expect_equal(class(t), c("type", "datetime"))
  s <- "date(format = '%Y-%m-%d')"
  t <- type_parse(s)
  expect_true(t == "date")
  expect_true(t$format == "%Y-%m-%d")
  expect_equal(class(t), c("type", "date"))
  s <- "numeric(dec = 2, sign = '+')"
  t <- type_parse(s)
  expect_true(t == "numeric")
  expect_true(t$dec == 2)
  expect_true(t$sign == '+')
  expect_equal(class(t), c("type", "numeric"))
})