FROM rocker/r-ver:4.4.2
RUN apt-get update && apt-get install -y  libcurl4-openssl-dev libicu-dev libssl-dev libx11-dev libxml2-dev make pandoc zlib1g-dev && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /usr/local/lib/R/etc/ /usr/lib/R/etc/
RUN echo "options(repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl', Ncpus = 4)" | tee /usr/local/lib/R/etc/Rprofile.site | tee /usr/lib/R/etc/Rprofile.site
RUN R -e 'install.packages("remotes")'
RUN Rscript -e 'remotes::install_version("cli",upgrade="never", version = "3.6.3")'
RUN Rscript -e 'remotes::install_version("rlang",upgrade="never", version = "1.1.4")'
RUN Rscript -e 'remotes::install_version("magrittr",upgrade="never", version = "2.0.3")'
RUN Rscript -e 'remotes::install_version("jsonlite",upgrade="never", version = "1.8.8")'
RUN Rscript -e 'remotes::install_version("withr",upgrade="never", version = "3.0.0")'
RUN Rscript -e 'remotes::install_version("yaml",upgrade="never", version = "2.3.9")'
RUN Rscript -e 'remotes::install_version("digest",upgrade="never", version = "0.6.36")'
RUN Rscript -e 'remotes::install_version("base64enc",upgrade="never", version = "0.1-3")'
RUN Rscript -e 'remotes::install_version("xtable",upgrade="never", version = "1.8-4")'
RUN Rscript -e 'remotes::install_version("rmarkdown",upgrade="never", version = "2.27")'
RUN Rscript -e 'remotes::install_version("knitr",upgrade="never", version = "1.48")'
RUN Rscript -e 'remotes::install_version("tibble",upgrade="never", version = "3.2.1")'
RUN Rscript -e 'remotes::install_version("stringr",upgrade="never", version = "1.5.1")'
RUN Rscript -e 'remotes::install_version("httr",upgrade="never", version = "1.4.7")'
RUN Rscript -e 'remotes::install_version("scales",upgrade="never", version = "1.3.0")'
RUN Rscript -e 'remotes::install_version("shiny",upgrade="never", version = "1.10.0")'
RUN Rscript -e 'remotes::install_version("purrr",upgrade="never", version = "1.0.2")'
RUN Rscript -e 'remotes::install_version("dplyr",upgrade="never", version = "1.1.4")'
RUN Rscript -e 'remotes::install_version("vcr",upgrade="never", version = NA)'
RUN Rscript -e 'remotes::install_version("covr",upgrade="never", version = NA)'
RUN Rscript -e 'remotes::install_version("ggplot2",upgrade="never", version = "3.5.1")'
RUN Rscript -e 'remotes::install_version("miniUI",upgrade="never", version = "0.1.1.1")'
RUN Rscript -e 'remotes::install_version("DT",upgrade="never", version = "0.33")'
RUN Rscript -e 'remotes::install_version("testthat",upgrade="never", version = "3.2.1.1")'
RUN Rscript -e 'remotes::install_version("tidyr",upgrade="never", version = "1.3.1")'
RUN Rscript -e 'remotes::install_version("readxl",upgrade="never", version = "1.4.3")'
RUN Rscript -e 'remotes::install_version("XML",upgrade="never", version = "3.99-0.18")'
RUN Rscript -e 'remotes::install_version("ascii",upgrade="never", version = "2.6")'
RUN Rscript -e 'remotes::install_version("rvest",upgrade="never", version = "1.0.4")'
RUN Rscript -e 'remotes::install_version("readr",upgrade="never", version = "2.1.5")'
RUN Rscript -e 'remotes::install_version("proto",upgrade="never", version = "1.0.0")'
RUN Rscript -e 'remotes::install_version("bizdays",upgrade="never", version = "1.0.16")'
RUN mkdir /build_zone
ADD . /build_zone
WORKDIR /build_zone
RUN R -e 'remotes::install_local(upgrade="never")'
RUN rm -rf /build_zone
